version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 23940130
      API_HASH: 4d717a6f888e37b7ebde0ace80cd22c6
      BOT_TOKEN: 7443034654:AAH83ai22x0R_um_D4zHToFIiCAv8M1q4Co
      SESSION: BQFtTCIAP6lFhRrJrxceGpvYZPb4dBa-v9iSs5FU7suGA1xBpqG3G6UwRnsKFfOvVgg8DJFP_K2GUq_aHOPm7H4FTThkNaTdDraPazNCbNylt-yDS0J-h3-OsW9153FGy4vJZPa0N6ABEBrV9WkgZWD0Kib-XVhzJna8hBOnt32WM_CQdDRNy65n6b-NtXWGRVZ33sTp3t7s0fNfEvsQTYYgQfdPv5NHQvym1R0eF8q-dwtbe9lfqfqWrVIN03EMRznVtd9jufpHb_oy_-EmBZDmfAHzXq_ILjO3xC31toHsuGFtfEx3JcWggyLRwZjcNpMLviU9f-reScfm6QU2bx_sTyhAAAAAE81sz9AA
      AUTH: -1005315677437
      FORCESUB: yuy1326
